// flow-typed signature: 91b83b05af64cb50b7b768be47aff0e4
// flow-typed version: <<STUB>>/async_v^0.9/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async/lib/async' {
  declare module.exports: any;
}

declare module 'async/support/sync-package-managers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async/lib/async.js' {
  declare module.exports: $Exports<'async/lib/async'>;
}
declare module 'async/support/sync-package-managers.js' {
  declare module.exports: $Exports<'async/support/sync-package-managers'>;
}
