// flow-typed signature: 30fa030855d4607def54cfe6d8c8a587
// flow-typed version: <<STUB>>/bluebird_v^2.9/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bluebird'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bluebird' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bluebird/js/browser/bluebird' {
  declare module.exports: any;
}

declare module 'bluebird/js/browser/bluebird.min' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/any' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/assert' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/async' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/bind' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/bluebird' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/call_get' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/cancel' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/captured_trace' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/catch_filter' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/context' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/debuggability' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/direct_resolve' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/each' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/errors' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/es5' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/filter' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/finally' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/generators' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/join' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/map' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/method' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/nodeify' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/progress' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/promise_array' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/promise_resolver' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/promise' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/promisify' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/props' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/queue' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/race' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/reduce' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/schedule' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/settle' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/some' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/synchronous_inspection' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/thenables' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/timers' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/using' {
  declare module.exports: any;
}

declare module 'bluebird/js/main/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bluebird/js/browser/bluebird.js' {
  declare module.exports: $Exports<'bluebird/js/browser/bluebird'>;
}
declare module 'bluebird/js/browser/bluebird.min.js' {
  declare module.exports: $Exports<'bluebird/js/browser/bluebird.min'>;
}
declare module 'bluebird/js/main/any.js' {
  declare module.exports: $Exports<'bluebird/js/main/any'>;
}
declare module 'bluebird/js/main/assert.js' {
  declare module.exports: $Exports<'bluebird/js/main/assert'>;
}
declare module 'bluebird/js/main/async.js' {
  declare module.exports: $Exports<'bluebird/js/main/async'>;
}
declare module 'bluebird/js/main/bind.js' {
  declare module.exports: $Exports<'bluebird/js/main/bind'>;
}
declare module 'bluebird/js/main/bluebird.js' {
  declare module.exports: $Exports<'bluebird/js/main/bluebird'>;
}
declare module 'bluebird/js/main/call_get.js' {
  declare module.exports: $Exports<'bluebird/js/main/call_get'>;
}
declare module 'bluebird/js/main/cancel.js' {
  declare module.exports: $Exports<'bluebird/js/main/cancel'>;
}
declare module 'bluebird/js/main/captured_trace.js' {
  declare module.exports: $Exports<'bluebird/js/main/captured_trace'>;
}
declare module 'bluebird/js/main/catch_filter.js' {
  declare module.exports: $Exports<'bluebird/js/main/catch_filter'>;
}
declare module 'bluebird/js/main/context.js' {
  declare module.exports: $Exports<'bluebird/js/main/context'>;
}
declare module 'bluebird/js/main/debuggability.js' {
  declare module.exports: $Exports<'bluebird/js/main/debuggability'>;
}
declare module 'bluebird/js/main/direct_resolve.js' {
  declare module.exports: $Exports<'bluebird/js/main/direct_resolve'>;
}
declare module 'bluebird/js/main/each.js' {
  declare module.exports: $Exports<'bluebird/js/main/each'>;
}
declare module 'bluebird/js/main/errors.js' {
  declare module.exports: $Exports<'bluebird/js/main/errors'>;
}
declare module 'bluebird/js/main/es5.js' {
  declare module.exports: $Exports<'bluebird/js/main/es5'>;
}
declare module 'bluebird/js/main/filter.js' {
  declare module.exports: $Exports<'bluebird/js/main/filter'>;
}
declare module 'bluebird/js/main/finally.js' {
  declare module.exports: $Exports<'bluebird/js/main/finally'>;
}
declare module 'bluebird/js/main/generators.js' {
  declare module.exports: $Exports<'bluebird/js/main/generators'>;
}
declare module 'bluebird/js/main/join.js' {
  declare module.exports: $Exports<'bluebird/js/main/join'>;
}
declare module 'bluebird/js/main/map.js' {
  declare module.exports: $Exports<'bluebird/js/main/map'>;
}
declare module 'bluebird/js/main/method.js' {
  declare module.exports: $Exports<'bluebird/js/main/method'>;
}
declare module 'bluebird/js/main/nodeify.js' {
  declare module.exports: $Exports<'bluebird/js/main/nodeify'>;
}
declare module 'bluebird/js/main/progress.js' {
  declare module.exports: $Exports<'bluebird/js/main/progress'>;
}
declare module 'bluebird/js/main/promise_array.js' {
  declare module.exports: $Exports<'bluebird/js/main/promise_array'>;
}
declare module 'bluebird/js/main/promise_resolver.js' {
  declare module.exports: $Exports<'bluebird/js/main/promise_resolver'>;
}
declare module 'bluebird/js/main/promise.js' {
  declare module.exports: $Exports<'bluebird/js/main/promise'>;
}
declare module 'bluebird/js/main/promisify.js' {
  declare module.exports: $Exports<'bluebird/js/main/promisify'>;
}
declare module 'bluebird/js/main/props.js' {
  declare module.exports: $Exports<'bluebird/js/main/props'>;
}
declare module 'bluebird/js/main/queue.js' {
  declare module.exports: $Exports<'bluebird/js/main/queue'>;
}
declare module 'bluebird/js/main/race.js' {
  declare module.exports: $Exports<'bluebird/js/main/race'>;
}
declare module 'bluebird/js/main/reduce.js' {
  declare module.exports: $Exports<'bluebird/js/main/reduce'>;
}
declare module 'bluebird/js/main/schedule.js' {
  declare module.exports: $Exports<'bluebird/js/main/schedule'>;
}
declare module 'bluebird/js/main/settle.js' {
  declare module.exports: $Exports<'bluebird/js/main/settle'>;
}
declare module 'bluebird/js/main/some.js' {
  declare module.exports: $Exports<'bluebird/js/main/some'>;
}
declare module 'bluebird/js/main/synchronous_inspection.js' {
  declare module.exports: $Exports<'bluebird/js/main/synchronous_inspection'>;
}
declare module 'bluebird/js/main/thenables.js' {
  declare module.exports: $Exports<'bluebird/js/main/thenables'>;
}
declare module 'bluebird/js/main/timers.js' {
  declare module.exports: $Exports<'bluebird/js/main/timers'>;
}
declare module 'bluebird/js/main/using.js' {
  declare module.exports: $Exports<'bluebird/js/main/using'>;
}
declare module 'bluebird/js/main/util.js' {
  declare module.exports: $Exports<'bluebird/js/main/util'>;
}
