// flow-typed signature: b38085b9a97a4ce9011e84494f79f81f
// flow-typed version: <<STUB>>/coffee-react_v^5.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffee-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffee-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coffee-react/lib/browser' {
  declare module.exports: any;
}

declare module 'coffee-react/lib/coffee-react-script' {
  declare module.exports: any;
}

declare module 'coffee-react/lib/command' {
  declare module.exports: any;
}

declare module 'coffee-react/lib/helpers' {
  declare module.exports: any;
}

declare module 'coffee-react/lib/js-syntax-transform' {
  declare module.exports: any;
}

declare module 'coffee-react/lib/register' {
  declare module.exports: any;
}

declare module 'coffee-react/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coffee-react/lib/browser.js' {
  declare module.exports: $Exports<'coffee-react/lib/browser'>;
}
declare module 'coffee-react/lib/coffee-react-script.js' {
  declare module.exports: $Exports<'coffee-react/lib/coffee-react-script'>;
}
declare module 'coffee-react/lib/command.js' {
  declare module.exports: $Exports<'coffee-react/lib/command'>;
}
declare module 'coffee-react/lib/helpers.js' {
  declare module.exports: $Exports<'coffee-react/lib/helpers'>;
}
declare module 'coffee-react/lib/js-syntax-transform.js' {
  declare module.exports: $Exports<'coffee-react/lib/js-syntax-transform'>;
}
declare module 'coffee-react/lib/register.js' {
  declare module.exports: $Exports<'coffee-react/lib/register'>;
}
declare module 'coffee-react/register.js' {
  declare module.exports: $Exports<'coffee-react/register'>;
}
