// flow-typed signature: ec520c35406ede6f56a1067509cd5d9f
// flow-typed version: <<STUB>>/electron-spellchecker_v0.2.15/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-spellchecker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-spellchecker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-spellchecker/lib/babel-maybefill' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/context-menu-builder' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/context-menu-listener' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/custom-operators' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/dictionary-sync' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/fake-local-storage' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/fallback-locales' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/index' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/node-spellchecker' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/promisify' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/spell-check-handler' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/lib/utility' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/babel-maybefill' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/context-menu-builder' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/context-menu-listener' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/custom-operators' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/dictionary-sync' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/fake-local-storage' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/fallback-locales' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/index' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/node-spellchecker' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/promisify' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/spell-check-handler' {
  declare module.exports: any;
}

declare module 'electron-spellchecker/src/utility' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-spellchecker/lib/babel-maybefill.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/babel-maybefill'>;
}
declare module 'electron-spellchecker/lib/context-menu-builder.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/context-menu-builder'>;
}
declare module 'electron-spellchecker/lib/context-menu-listener.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/context-menu-listener'>;
}
declare module 'electron-spellchecker/lib/custom-operators.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/custom-operators'>;
}
declare module 'electron-spellchecker/lib/dictionary-sync.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/dictionary-sync'>;
}
declare module 'electron-spellchecker/lib/fake-local-storage.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/fake-local-storage'>;
}
declare module 'electron-spellchecker/lib/fallback-locales.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/fallback-locales'>;
}
declare module 'electron-spellchecker/lib/index.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/index'>;
}
declare module 'electron-spellchecker/lib/node-spellchecker.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/node-spellchecker'>;
}
declare module 'electron-spellchecker/lib/promisify.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/promisify'>;
}
declare module 'electron-spellchecker/lib/spell-check-handler.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/spell-check-handler'>;
}
declare module 'electron-spellchecker/lib/utility.js' {
  declare module.exports: $Exports<'electron-spellchecker/lib/utility'>;
}
declare module 'electron-spellchecker/src/babel-maybefill.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/babel-maybefill'>;
}
declare module 'electron-spellchecker/src/context-menu-builder.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/context-menu-builder'>;
}
declare module 'electron-spellchecker/src/context-menu-listener.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/context-menu-listener'>;
}
declare module 'electron-spellchecker/src/custom-operators.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/custom-operators'>;
}
declare module 'electron-spellchecker/src/dictionary-sync.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/dictionary-sync'>;
}
declare module 'electron-spellchecker/src/fake-local-storage.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/fake-local-storage'>;
}
declare module 'electron-spellchecker/src/fallback-locales.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/fallback-locales'>;
}
declare module 'electron-spellchecker/src/index.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/index'>;
}
declare module 'electron-spellchecker/src/node-spellchecker.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/node-spellchecker'>;
}
declare module 'electron-spellchecker/src/promisify.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/promisify'>;
}
declare module 'electron-spellchecker/src/spell-check-handler.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/spell-check-handler'>;
}
declare module 'electron-spellchecker/src/utility.js' {
  declare module.exports: $Exports<'electron-spellchecker/src/utility'>;
}
