// flow-typed signature: 4a0c8298588b363759b552b501d4d895
// flow-typed version: <<STUB>>/emissary_v^1.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emissary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'emissary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emissary/lib/behavior' {
  declare module.exports: any;
}

declare module 'emissary/lib/emissary' {
  declare module.exports: any;
}

declare module 'emissary/lib/emitter' {
  declare module.exports: any;
}

declare module 'emissary/lib/helpers' {
  declare module.exports: any;
}

declare module 'emissary/lib/signal' {
  declare module.exports: any;
}

declare module 'emissary/lib/subscriber' {
  declare module.exports: any;
}

declare module 'emissary/lib/subscription' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emissary/lib/behavior.js' {
  declare module.exports: $Exports<'emissary/lib/behavior'>;
}
declare module 'emissary/lib/emissary.js' {
  declare module.exports: $Exports<'emissary/lib/emissary'>;
}
declare module 'emissary/lib/emitter.js' {
  declare module.exports: $Exports<'emissary/lib/emitter'>;
}
declare module 'emissary/lib/helpers.js' {
  declare module.exports: $Exports<'emissary/lib/helpers'>;
}
declare module 'emissary/lib/signal.js' {
  declare module.exports: $Exports<'emissary/lib/signal'>;
}
declare module 'emissary/lib/subscriber.js' {
  declare module.exports: $Exports<'emissary/lib/subscriber'>;
}
declare module 'emissary/lib/subscription.js' {
  declare module.exports: $Exports<'emissary/lib/subscription'>;
}
