// flow-typed signature: 8e472e754dfa2dccdd98e74d750e3d09
// flow-typed version: <<STUB>>/event-kit_v^1.0.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'event-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'event-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'event-kit/lib/composite-disposable' {
  declare module.exports: any;
}

declare module 'event-kit/lib/disposable' {
  declare module.exports: any;
}

declare module 'event-kit/lib/emitter' {
  declare module.exports: any;
}

declare module 'event-kit/lib/event-kit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'event-kit/lib/composite-disposable.js' {
  declare module.exports: $Exports<'event-kit/lib/composite-disposable'>;
}
declare module 'event-kit/lib/disposable.js' {
  declare module.exports: $Exports<'event-kit/lib/disposable'>;
}
declare module 'event-kit/lib/emitter.js' {
  declare module.exports: $Exports<'event-kit/lib/emitter'>;
}
declare module 'event-kit/lib/event-kit.js' {
  declare module.exports: $Exports<'event-kit/lib/event-kit'>;
}
