// flow-typed signature: c70200e03cbdb2eddeed00eeb77a3465
// flow-typed version: <<STUB>>/immutable_v3.7.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutable/contrib/cursor/index' {
  declare module.exports: any;
}

declare module 'immutable/dist/immutable' {
  declare module.exports: any;
}

declare module 'immutable/dist/immutable.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutable/contrib/cursor/index.js' {
  declare module.exports: $Exports<'immutable/contrib/cursor/index'>;
}
declare module 'immutable/dist/immutable.js' {
  declare module.exports: $Exports<'immutable/dist/immutable'>;
}
declare module 'immutable/dist/immutable.min.js' {
  declare module.exports: $Exports<'immutable/dist/immutable.min'>;
}
