// flow-typed signature: 5a7f5d9591c79b10615b7c9b2ed5169e
// flow-typed version: <<STUB>>/moment-timezone_v0.5.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-timezone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-timezone/builds/moment-timezone-with-data-2010-2020' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data-2010-2020.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/moment-timezone-utils' {
  declare module.exports: any;
}

declare module 'moment-timezone/moment-timezone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-timezone/builds/moment-timezone-with-data-2010-2020.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-2010-2020'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-2010-2020.min'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data.min'>;
}
declare module 'moment-timezone/builds/moment-timezone.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone.min'>;
}
declare module 'moment-timezone/index' {
  declare module.exports: $Exports<'moment-timezone'>;
}
declare module 'moment-timezone/index.js' {
  declare module.exports: $Exports<'moment-timezone'>;
}
declare module 'moment-timezone/moment-timezone-utils.js' {
  declare module.exports: $Exports<'moment-timezone/moment-timezone-utils'>;
}
declare module 'moment-timezone/moment-timezone.js' {
  declare module.exports: $Exports<'moment-timezone/moment-timezone'>;
}
