// flow-typed signature: 4e16fc341f1804a12b863b70e6f7fb04
// flow-typed version: <<STUB>>/moment-round_v^1.0.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-round'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-round' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-round/dist/moment-round' {
  declare module.exports: any;
}

declare module 'moment-round/dist/moment-round.min' {
  declare module.exports: any;
}

declare module 'moment-round/gulpfile' {
  declare module.exports: any;
}

declare module 'moment-round/src/moment-round' {
  declare module.exports: any;
}

declare module 'moment-round/test/moment-round' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-round/dist/moment-round.js' {
  declare module.exports: $Exports<'moment-round/dist/moment-round'>;
}
declare module 'moment-round/dist/moment-round.min.js' {
  declare module.exports: $Exports<'moment-round/dist/moment-round.min'>;
}
declare module 'moment-round/gulpfile.js' {
  declare module.exports: $Exports<'moment-round/gulpfile'>;
}
declare module 'moment-round/src/moment-round.js' {
  declare module.exports: $Exports<'moment-round/src/moment-round'>;
}
declare module 'moment-round/test/moment-round.js' {
  declare module.exports: $Exports<'moment-round/test/moment-round'>;
}
