// flow-typed signature: 440161a43b6c19c9972ba3bd80b84ac5
// flow-typed version: <<STUB>>/nslog_v^3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nslog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nslog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nslog/lib/nslog' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nslog/lib/nslog.js' {
  declare module.exports: $Exports<'nslog/lib/nslog'>;
}
