// flow-typed signature: e077122622e55c0d4e43ca60490e6216
// flow-typed version: <<STUB>>/promise-queue_v2.1.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-queue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-queue/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-queue/index' {
  declare module.exports: $Exports<'promise-queue'>;
}
declare module 'promise-queue/index.js' {
  declare module.exports: $Exports<'promise-queue'>;
}
declare module 'promise-queue/lib/index.js' {
  declare module.exports: $Exports<'promise-queue/lib/index'>;
}
