// flow-typed signature: 2ccedcf0f45e3e25837b888898e6317b
// flow-typed version: <<STUB>>/property-accessors_v^1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'property-accessors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'property-accessors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'property-accessors/lib/property-accessors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'property-accessors/lib/property-accessors.js' {
  declare module.exports: $Exports<'property-accessors/lib/property-accessors'>;
}
