// flow-typed signature: 60910949c7ed7a3c87d9ff703efa34c3
// flow-typed version: <<STUB>>/request_v^2.53/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request/lib/auth' {
  declare module.exports: any;
}

declare module 'request/lib/cookies' {
  declare module.exports: any;
}

declare module 'request/lib/getProxyFromURI' {
  declare module.exports: any;
}

declare module 'request/lib/har' {
  declare module.exports: any;
}

declare module 'request/lib/helpers' {
  declare module.exports: any;
}

declare module 'request/lib/multipart' {
  declare module.exports: any;
}

declare module 'request/lib/oauth' {
  declare module.exports: any;
}

declare module 'request/lib/querystring' {
  declare module.exports: any;
}

declare module 'request/lib/redirect' {
  declare module.exports: any;
}

declare module 'request/lib/tunnel' {
  declare module.exports: any;
}

declare module 'request/request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request/index' {
  declare module.exports: $Exports<'request'>;
}
declare module 'request/index.js' {
  declare module.exports: $Exports<'request'>;
}
declare module 'request/lib/auth.js' {
  declare module.exports: $Exports<'request/lib/auth'>;
}
declare module 'request/lib/cookies.js' {
  declare module.exports: $Exports<'request/lib/cookies'>;
}
declare module 'request/lib/getProxyFromURI.js' {
  declare module.exports: $Exports<'request/lib/getProxyFromURI'>;
}
declare module 'request/lib/har.js' {
  declare module.exports: $Exports<'request/lib/har'>;
}
declare module 'request/lib/helpers.js' {
  declare module.exports: $Exports<'request/lib/helpers'>;
}
declare module 'request/lib/multipart.js' {
  declare module.exports: $Exports<'request/lib/multipart'>;
}
declare module 'request/lib/oauth.js' {
  declare module.exports: $Exports<'request/lib/oauth'>;
}
declare module 'request/lib/querystring.js' {
  declare module.exports: $Exports<'request/lib/querystring'>;
}
declare module 'request/lib/redirect.js' {
  declare module.exports: $Exports<'request/lib/redirect'>;
}
declare module 'request/lib/tunnel.js' {
  declare module.exports: $Exports<'request/lib/tunnel'>;
}
declare module 'request/request.js' {
  declare module.exports: $Exports<'request/request'>;
}
