// flow-typed signature: 4a60462ed4b8abf5d719430a92cc400c
// flow-typed version: <<STUB>>/rx-lite_v^4.0.7/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rx-lite/rx.lite' {
  declare module.exports: any;
}

declare module 'rx-lite/rx.lite.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rx-lite/rx.lite.js' {
  declare module.exports: $Exports<'rx-lite/rx.lite'>;
}
declare module 'rx-lite/rx.lite.min.js' {
  declare module.exports: $Exports<'rx-lite/rx.lite.min'>;
}
