// flow-typed signature: efffd9eb4c82ffe4bd1926ff7c32fab6
// flow-typed version: <<STUB>>/semver_v^4.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semver/semver.browser' {
  declare module.exports: any;
}

declare module 'semver/semver' {
  declare module.exports: any;
}

declare module 'semver/semver.min' {
  declare module.exports: any;
}

declare module 'semver/test/amd' {
  declare module.exports: any;
}

declare module 'semver/test/big-numbers' {
  declare module.exports: any;
}

declare module 'semver/test/clean' {
  declare module.exports: any;
}

declare module 'semver/test/gtr' {
  declare module.exports: any;
}

declare module 'semver/test/index' {
  declare module.exports: any;
}

declare module 'semver/test/ltr' {
  declare module.exports: any;
}

declare module 'semver/test/major-minor-patch' {
  declare module.exports: any;
}

declare module 'semver/test/no-module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semver/semver.browser.js' {
  declare module.exports: $Exports<'semver/semver.browser'>;
}
declare module 'semver/semver.js' {
  declare module.exports: $Exports<'semver/semver'>;
}
declare module 'semver/semver.min.js' {
  declare module.exports: $Exports<'semver/semver.min'>;
}
declare module 'semver/test/amd.js' {
  declare module.exports: $Exports<'semver/test/amd'>;
}
declare module 'semver/test/big-numbers.js' {
  declare module.exports: $Exports<'semver/test/big-numbers'>;
}
declare module 'semver/test/clean.js' {
  declare module.exports: $Exports<'semver/test/clean'>;
}
declare module 'semver/test/gtr.js' {
  declare module.exports: $Exports<'semver/test/gtr'>;
}
declare module 'semver/test/index.js' {
  declare module.exports: $Exports<'semver/test/index'>;
}
declare module 'semver/test/ltr.js' {
  declare module.exports: $Exports<'semver/test/ltr'>;
}
declare module 'semver/test/major-minor-patch.js' {
  declare module.exports: $Exports<'semver/test/major-minor-patch'>;
}
declare module 'semver/test/no-module.js' {
  declare module.exports: $Exports<'semver/test/no-module'>;
}
