// flow-typed signature: 888faf6d57202783412c28c56f321af3
// flow-typed version: <<STUB>>/temp_v^0.8/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'temp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'temp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'temp/examples/grepcount' {
  declare module.exports: any;
}

declare module 'temp/examples/pdfcreator' {
  declare module.exports: any;
}

declare module 'temp/lib/temp' {
  declare module.exports: any;
}

declare module 'temp/no_cleanup_on_exit' {
  declare module.exports: any;
}

declare module 'temp/no_cleanup_on_exit.spec' {
  declare module.exports: any;
}

declare module 'temp/no_cleanup' {
  declare module.exports: any;
}

declare module 'temp/test/temp-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'temp/examples/grepcount.js' {
  declare module.exports: $Exports<'temp/examples/grepcount'>;
}
declare module 'temp/examples/pdfcreator.js' {
  declare module.exports: $Exports<'temp/examples/pdfcreator'>;
}
declare module 'temp/lib/temp.js' {
  declare module.exports: $Exports<'temp/lib/temp'>;
}
declare module 'temp/no_cleanup_on_exit.js' {
  declare module.exports: $Exports<'temp/no_cleanup_on_exit'>;
}
declare module 'temp/no_cleanup_on_exit.spec.js' {
  declare module.exports: $Exports<'temp/no_cleanup_on_exit.spec'>;
}
declare module 'temp/no_cleanup.js' {
  declare module.exports: $Exports<'temp/no_cleanup'>;
}
declare module 'temp/test/temp-test.js' {
  declare module.exports: $Exports<'temp/test/temp-test'>;
}
