// flow-typed signature: 7e9ef0f42c23ec0a858baf8b28b45890
// flow-typed version: <<STUB>>/windows-shortcuts_vemorikawa/windows-shortcuts#b0a0fc7/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'windows-shortcuts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'windows-shortcuts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'windows-shortcuts/lib/windows-shortcuts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'windows-shortcuts/lib/windows-shortcuts.js' {
  declare module.exports: $Exports<'windows-shortcuts/lib/windows-shortcuts'>;
}
