// flow-typed signature: cbec7973a55cf62dbb89630cf4c84906
// flow-typed version: <<STUB>>/chromium-net-errors_v1.0.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chromium-net-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chromium-net-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'chromium-net-errors/index' {
  declare module.exports: $Exports<'chromium-net-errors'>;
}
declare module 'chromium-net-errors/index.js' {
  declare module.exports: $Exports<'chromium-net-errors'>;
}
