// flow-typed signature: 605c1ba1e8f9b0cbd637cf69db27235d
// flow-typed version: <<STUB>>/chrono-node_v^1.1.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrono-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrono-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrono-node/chrono' {
  declare module.exports: any;
}

declare module 'chrono-node/chrono.min' {
  declare module.exports: any;
}

declare module 'chrono-node/karma.conf' {
  declare module.exports: any;
}

declare module 'chrono-node/src/chrono' {
  declare module.exports: any;
}

declare module 'chrono-node/src/options' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENISOFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENMonthNameMiddleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENSlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENSlashDateFormatStartWithYearParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENSlashMonthFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENTimeAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/EN/ENWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ES/ESCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ES/ESDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ES/ESMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ES/ESSlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ES/ESTimeAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ES/ESTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ES/ESWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/JP/JPCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/JP/JPStandardParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/parser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ConcordanceTimezoneRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/EN/ENMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/EN/ENMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/EN/ENMergeWeekdayRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ExtractTimezoneAbbrRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ExtractTimezoneOffsetRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/JP/JPMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/OverlapRemovalRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/refiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/UnlikelyFormatFilter' {
  declare module.exports: any;
}

declare module 'chrono-node/src/result' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/EN' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/ES' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/JP' {
  declare module.exports: any;
}

declare module 'chrono-node/test/qunit/jquery-1.7.1.min' {
  declare module.exports: any;
}

declare module 'chrono-node/test/qunit/qunit-git' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_casual' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_deadline' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_inter_std' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_little_endian' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_middle_endian' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_slash' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_time_ago' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_time_exp' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en_weekday' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_en' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_es_casual' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_es_deadline' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_es_little_endian' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_es_slash' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_es_time_ago' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_es_time_exp' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_example' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_jp_casual' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_jp_standard' {
  declare module.exports: any;
}

declare module 'chrono-node/test/test_system' {
  declare module.exports: any;
}

declare module 'chrono-node/timezone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrono-node/chrono.js' {
  declare module.exports: $Exports<'chrono-node/chrono'>;
}
declare module 'chrono-node/chrono.min.js' {
  declare module.exports: $Exports<'chrono-node/chrono.min'>;
}
declare module 'chrono-node/karma.conf.js' {
  declare module.exports: $Exports<'chrono-node/karma.conf'>;
}
declare module 'chrono-node/src/chrono.js' {
  declare module.exports: $Exports<'chrono-node/src/chrono'>;
}
declare module 'chrono-node/src/options.js' {
  declare module.exports: $Exports<'chrono-node/src/options'>;
}
declare module 'chrono-node/src/parsers/EN/ENCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENDeadlineFormatParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENISOFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENISOFormatParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENMonthNameMiddleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENMonthNameMiddleEndianParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENMonthNameParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENSlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENSlashDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENSlashDateFormatStartWithYearParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENSlashDateFormatStartWithYearParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENSlashMonthFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENSlashMonthFormatParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENTimeAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENTimeAgoFormatParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENTimeExpressionParser'>;
}
declare module 'chrono-node/src/parsers/EN/ENWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/EN/ENWeekdayParser'>;
}
declare module 'chrono-node/src/parsers/ES/ESCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ES/ESCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/ES/ESDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ES/ESDeadlineFormatParser'>;
}
declare module 'chrono-node/src/parsers/ES/ESMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ES/ESMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/src/parsers/ES/ESSlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ES/ESSlashDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/ES/ESTimeAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ES/ESTimeAgoFormatParser'>;
}
declare module 'chrono-node/src/parsers/ES/ESTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ES/ESTimeExpressionParser'>;
}
declare module 'chrono-node/src/parsers/ES/ESWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ES/ESWeekdayParser'>;
}
declare module 'chrono-node/src/parsers/JP/JPCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/JP/JPCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/JP/JPStandardParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/JP/JPStandardParser'>;
}
declare module 'chrono-node/src/parsers/parser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/parser'>;
}
declare module 'chrono-node/src/refiners/ConcordanceTimezoneRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ConcordanceTimezoneRefiner'>;
}
declare module 'chrono-node/src/refiners/EN/ENMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/EN/ENMergeDateRangeRefiner'>;
}
declare module 'chrono-node/src/refiners/EN/ENMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/EN/ENMergeDateTimeRefiner'>;
}
declare module 'chrono-node/src/refiners/EN/ENMergeWeekdayRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/EN/ENMergeWeekdayRefiner'>;
}
declare module 'chrono-node/src/refiners/ExtractTimezoneAbbrRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ExtractTimezoneAbbrRefiner'>;
}
declare module 'chrono-node/src/refiners/ExtractTimezoneOffsetRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ExtractTimezoneOffsetRefiner'>;
}
declare module 'chrono-node/src/refiners/JP/JPMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/JP/JPMergeDateRangeRefiner'>;
}
declare module 'chrono-node/src/refiners/OverlapRemovalRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/OverlapRemovalRefiner'>;
}
declare module 'chrono-node/src/refiners/refiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/refiner'>;
}
declare module 'chrono-node/src/refiners/UnlikelyFormatFilter.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/UnlikelyFormatFilter'>;
}
declare module 'chrono-node/src/result.js' {
  declare module.exports: $Exports<'chrono-node/src/result'>;
}
declare module 'chrono-node/src/utils/EN.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/EN'>;
}
declare module 'chrono-node/src/utils/ES.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/ES'>;
}
declare module 'chrono-node/src/utils/JP.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/JP'>;
}
declare module 'chrono-node/test/qunit/jquery-1.7.1.min.js' {
  declare module.exports: $Exports<'chrono-node/test/qunit/jquery-1.7.1.min'>;
}
declare module 'chrono-node/test/qunit/qunit-git.js' {
  declare module.exports: $Exports<'chrono-node/test/qunit/qunit-git'>;
}
declare module 'chrono-node/test/test_en_casual.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_casual'>;
}
declare module 'chrono-node/test/test_en_deadline.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_deadline'>;
}
declare module 'chrono-node/test/test_en_inter_std.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_inter_std'>;
}
declare module 'chrono-node/test/test_en_little_endian.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_little_endian'>;
}
declare module 'chrono-node/test/test_en_middle_endian.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_middle_endian'>;
}
declare module 'chrono-node/test/test_en_slash.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_slash'>;
}
declare module 'chrono-node/test/test_en_time_ago.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_time_ago'>;
}
declare module 'chrono-node/test/test_en_time_exp.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_time_exp'>;
}
declare module 'chrono-node/test/test_en_weekday.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en_weekday'>;
}
declare module 'chrono-node/test/test_en.js' {
  declare module.exports: $Exports<'chrono-node/test/test_en'>;
}
declare module 'chrono-node/test/test_es_casual.js' {
  declare module.exports: $Exports<'chrono-node/test/test_es_casual'>;
}
declare module 'chrono-node/test/test_es_deadline.js' {
  declare module.exports: $Exports<'chrono-node/test/test_es_deadline'>;
}
declare module 'chrono-node/test/test_es_little_endian.js' {
  declare module.exports: $Exports<'chrono-node/test/test_es_little_endian'>;
}
declare module 'chrono-node/test/test_es_slash.js' {
  declare module.exports: $Exports<'chrono-node/test/test_es_slash'>;
}
declare module 'chrono-node/test/test_es_time_ago.js' {
  declare module.exports: $Exports<'chrono-node/test/test_es_time_ago'>;
}
declare module 'chrono-node/test/test_es_time_exp.js' {
  declare module.exports: $Exports<'chrono-node/test/test_es_time_exp'>;
}
declare module 'chrono-node/test/test_example.js' {
  declare module.exports: $Exports<'chrono-node/test/test_example'>;
}
declare module 'chrono-node/test/test_jp_casual.js' {
  declare module.exports: $Exports<'chrono-node/test/test_jp_casual'>;
}
declare module 'chrono-node/test/test_jp_standard.js' {
  declare module.exports: $Exports<'chrono-node/test/test_jp_standard'>;
}
declare module 'chrono-node/test/test_system.js' {
  declare module.exports: $Exports<'chrono-node/test/test_system'>;
}
declare module 'chrono-node/timezone.js' {
  declare module.exports: $Exports<'chrono-node/timezone'>;
}
