// flow-typed signature: 626342745373b7fe88a59cd994e2a2f6
// flow-typed version: <<STUB>>/emoji-data_v^0.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-data/doc/javascript/application' {
  declare module.exports: any;
}

declare module 'emoji-data/doc/javascript/search' {
  declare module.exports: any;
}

declare module 'emoji-data/lib/emoji_char' {
  declare module.exports: any;
}

declare module 'emoji-data/lib/emoji_data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-data/doc/javascript/application.js' {
  declare module.exports: $Exports<'emoji-data/doc/javascript/application'>;
}
declare module 'emoji-data/doc/javascript/search.js' {
  declare module.exports: $Exports<'emoji-data/doc/javascript/search'>;
}
declare module 'emoji-data/lib/emoji_char.js' {
  declare module.exports: $Exports<'emoji-data/lib/emoji_char'>;
}
declare module 'emoji-data/lib/emoji_data.js' {
  declare module.exports: $Exports<'emoji-data/lib/emoji_data'>;
}
