// flow-typed signature: 6175325924d2de98f76ef111a222b305
// flow-typed version: <<STUB>>/guid_v0.0.10/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'guid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'guid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'guid/ender' {
  declare module.exports: any;
}

declare module 'guid/guid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'guid/ender.js' {
  declare module.exports: $Exports<'guid/ender'>;
}
declare module 'guid/guid.js' {
  declare module.exports: $Exports<'guid/guid'>;
}
