// flow-typed signature: 9f48f31dc218e6e62e6b270424951176
// flow-typed version: <<STUB>>/juice_v^1.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'juice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'juice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'juice/client' {
  declare module.exports: any;
}

declare module 'juice/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'juice/lib/cli' {
  declare module.exports: any;
}

declare module 'juice/lib/property' {
  declare module.exports: any;
}

declare module 'juice/lib/selector' {
  declare module.exports: any;
}

declare module 'juice/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'juice/client.js' {
  declare module.exports: $Exports<'juice/client'>;
}
declare module 'juice/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'juice/coverage/lcov-report/prettify'>;
}
declare module 'juice/index' {
  declare module.exports: $Exports<'juice'>;
}
declare module 'juice/index.js' {
  declare module.exports: $Exports<'juice'>;
}
declare module 'juice/lib/cli.js' {
  declare module.exports: $Exports<'juice/lib/cli'>;
}
declare module 'juice/lib/property.js' {
  declare module.exports: $Exports<'juice/lib/property'>;
}
declare module 'juice/lib/selector.js' {
  declare module.exports: $Exports<'juice/lib/selector'>;
}
declare module 'juice/lib/utils.js' {
  declare module.exports: $Exports<'juice/lib/utils'>;
}
