// flow-typed signature: c166461a36e70ffeec197253bf68f4a0
// flow-typed version: <<STUB>>/nock_v^2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nock/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'nock/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'nock/examples/_log' {
  declare module.exports: any;
}

declare module 'nock/examples/delay-connection' {
  declare module.exports: any;
}

declare module 'nock/examples/delay-response' {
  declare module.exports: any;
}

declare module 'nock/examples/net-connect-default-no-mock' {
  declare module.exports: any;
}

declare module 'nock/examples/net-connect-default-other-mock' {
  declare module.exports: any;
}

declare module 'nock/examples/net-connect-disabled-different-host' {
  declare module.exports: any;
}

declare module 'nock/examples/net-connect-mock-same-host-different-path' {
  declare module.exports: any;
}

declare module 'nock/examples/socket-delay-abort' {
  declare module.exports: any;
}

declare module 'nock/examples/socket-delay-no-abort' {
  declare module.exports: any;
}

declare module 'nock/lib/back' {
  declare module.exports: any;
}

declare module 'nock/lib/common' {
  declare module.exports: any;
}

declare module 'nock/lib/delayed_body' {
  declare module.exports: any;
}

declare module 'nock/lib/intercept' {
  declare module.exports: any;
}

declare module 'nock/lib/match_body' {
  declare module.exports: any;
}

declare module 'nock/lib/mixin' {
  declare module.exports: any;
}

declare module 'nock/lib/recorder' {
  declare module.exports: any;
}

declare module 'nock/lib/request_overrider' {
  declare module.exports: any;
}

declare module 'nock/lib/scope' {
  declare module.exports: any;
}

declare module 'nock/lib/socket' {
  declare module.exports: any;
}

declare module 'nock/tests/browserify-public/browserify-bundle' {
  declare module.exports: any;
}

declare module 'nock/tests/fixtures/browserify-script' {
  declare module.exports: any;
}

declare module 'nock/tests/test_aws_dynamo' {
  declare module.exports: any;
}

declare module 'nock/tests/test_back_2' {
  declare module.exports: any;
}

declare module 'nock/tests/test_back' {
  declare module.exports: any;
}

declare module 'nock/tests/test_basic_auth' {
  declare module.exports: any;
}

declare module 'nock/tests/test_browserify' {
  declare module.exports: any;
}

declare module 'nock/tests/test_common' {
  declare module.exports: any;
}

declare module 'nock/tests/test_data' {
  declare module.exports: any;
}

declare module 'nock/tests/test_dynamic_mock' {
  declare module.exports: any;
}

declare module 'nock/tests/test_https_allowunmocked' {
  declare module.exports: any;
}

declare module 'nock/tests/test_intercept' {
  declare module.exports: any;
}

declare module 'nock/tests/test_ipv6' {
  declare module.exports: any;
}

declare module 'nock/tests/test_isomorphic_fetch' {
  declare module.exports: any;
}

declare module 'nock/tests/test_net_connect' {
  declare module.exports: any;
}

declare module 'nock/tests/test_nock_off' {
  declare module.exports: any;
}

declare module 'nock/tests/test_recorder' {
  declare module.exports: any;
}

declare module 'nock/tests/test_redirects' {
  declare module.exports: any;
}

declare module 'nock/tests/test_request_promise' {
  declare module.exports: any;
}

declare module 'nock/tests/test_s3' {
  declare module.exports: any;
}

declare module 'nock/tests/test_url_encoding' {
  declare module.exports: any;
}

declare module 'nock/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nock/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'nock/coverage/lcov-report/prettify'>;
}
declare module 'nock/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'nock/coverage/lcov-report/sorter'>;
}
declare module 'nock/examples/_log.js' {
  declare module.exports: $Exports<'nock/examples/_log'>;
}
declare module 'nock/examples/delay-connection.js' {
  declare module.exports: $Exports<'nock/examples/delay-connection'>;
}
declare module 'nock/examples/delay-response.js' {
  declare module.exports: $Exports<'nock/examples/delay-response'>;
}
declare module 'nock/examples/net-connect-default-no-mock.js' {
  declare module.exports: $Exports<'nock/examples/net-connect-default-no-mock'>;
}
declare module 'nock/examples/net-connect-default-other-mock.js' {
  declare module.exports: $Exports<'nock/examples/net-connect-default-other-mock'>;
}
declare module 'nock/examples/net-connect-disabled-different-host.js' {
  declare module.exports: $Exports<'nock/examples/net-connect-disabled-different-host'>;
}
declare module 'nock/examples/net-connect-mock-same-host-different-path.js' {
  declare module.exports: $Exports<'nock/examples/net-connect-mock-same-host-different-path'>;
}
declare module 'nock/examples/socket-delay-abort.js' {
  declare module.exports: $Exports<'nock/examples/socket-delay-abort'>;
}
declare module 'nock/examples/socket-delay-no-abort.js' {
  declare module.exports: $Exports<'nock/examples/socket-delay-no-abort'>;
}
declare module 'nock/index' {
  declare module.exports: $Exports<'nock'>;
}
declare module 'nock/index.js' {
  declare module.exports: $Exports<'nock'>;
}
declare module 'nock/lib/back.js' {
  declare module.exports: $Exports<'nock/lib/back'>;
}
declare module 'nock/lib/common.js' {
  declare module.exports: $Exports<'nock/lib/common'>;
}
declare module 'nock/lib/delayed_body.js' {
  declare module.exports: $Exports<'nock/lib/delayed_body'>;
}
declare module 'nock/lib/intercept.js' {
  declare module.exports: $Exports<'nock/lib/intercept'>;
}
declare module 'nock/lib/match_body.js' {
  declare module.exports: $Exports<'nock/lib/match_body'>;
}
declare module 'nock/lib/mixin.js' {
  declare module.exports: $Exports<'nock/lib/mixin'>;
}
declare module 'nock/lib/recorder.js' {
  declare module.exports: $Exports<'nock/lib/recorder'>;
}
declare module 'nock/lib/request_overrider.js' {
  declare module.exports: $Exports<'nock/lib/request_overrider'>;
}
declare module 'nock/lib/scope.js' {
  declare module.exports: $Exports<'nock/lib/scope'>;
}
declare module 'nock/lib/socket.js' {
  declare module.exports: $Exports<'nock/lib/socket'>;
}
declare module 'nock/tests/browserify-public/browserify-bundle.js' {
  declare module.exports: $Exports<'nock/tests/browserify-public/browserify-bundle'>;
}
declare module 'nock/tests/fixtures/browserify-script.js' {
  declare module.exports: $Exports<'nock/tests/fixtures/browserify-script'>;
}
declare module 'nock/tests/test_aws_dynamo.js' {
  declare module.exports: $Exports<'nock/tests/test_aws_dynamo'>;
}
declare module 'nock/tests/test_back_2.js' {
  declare module.exports: $Exports<'nock/tests/test_back_2'>;
}
declare module 'nock/tests/test_back.js' {
  declare module.exports: $Exports<'nock/tests/test_back'>;
}
declare module 'nock/tests/test_basic_auth.js' {
  declare module.exports: $Exports<'nock/tests/test_basic_auth'>;
}
declare module 'nock/tests/test_browserify.js' {
  declare module.exports: $Exports<'nock/tests/test_browserify'>;
}
declare module 'nock/tests/test_common.js' {
  declare module.exports: $Exports<'nock/tests/test_common'>;
}
declare module 'nock/tests/test_data.js' {
  declare module.exports: $Exports<'nock/tests/test_data'>;
}
declare module 'nock/tests/test_dynamic_mock.js' {
  declare module.exports: $Exports<'nock/tests/test_dynamic_mock'>;
}
declare module 'nock/tests/test_https_allowunmocked.js' {
  declare module.exports: $Exports<'nock/tests/test_https_allowunmocked'>;
}
declare module 'nock/tests/test_intercept.js' {
  declare module.exports: $Exports<'nock/tests/test_intercept'>;
}
declare module 'nock/tests/test_ipv6.js' {
  declare module.exports: $Exports<'nock/tests/test_ipv6'>;
}
declare module 'nock/tests/test_isomorphic_fetch.js' {
  declare module.exports: $Exports<'nock/tests/test_isomorphic_fetch'>;
}
declare module 'nock/tests/test_net_connect.js' {
  declare module.exports: $Exports<'nock/tests/test_net_connect'>;
}
declare module 'nock/tests/test_nock_off.js' {
  declare module.exports: $Exports<'nock/tests/test_nock_off'>;
}
declare module 'nock/tests/test_recorder.js' {
  declare module.exports: $Exports<'nock/tests/test_recorder'>;
}
declare module 'nock/tests/test_redirects.js' {
  declare module.exports: $Exports<'nock/tests/test_redirects'>;
}
declare module 'nock/tests/test_request_promise.js' {
  declare module.exports: $Exports<'nock/tests/test_request_promise'>;
}
declare module 'nock/tests/test_s3.js' {
  declare module.exports: $Exports<'nock/tests/test_s3'>;
}
declare module 'nock/tests/test_url_encoding.js' {
  declare module.exports: $Exports<'nock/tests/test_url_encoding'>;
}
declare module 'nock/tests/test.js' {
  declare module.exports: $Exports<'nock/tests/test'>;
}
