// flow-typed signature: b53e022ec6f690bf421f6cd3a41ee167
// flow-typed version: <<STUB>>/reflux_v0.1.13/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reflux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reflux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reflux/dist/reflux' {
  declare module.exports: any;
}

declare module 'reflux/dist/reflux.min' {
  declare module.exports: any;
}

declare module 'reflux/Gruntfile' {
  declare module.exports: any;
}

declare module 'reflux/karma.conf' {
  declare module.exports: any;
}

declare module 'reflux/src/connect' {
  declare module.exports: any;
}

declare module 'reflux/src/createAction' {
  declare module.exports: any;
}

declare module 'reflux/src/createStore' {
  declare module.exports: any;
}

declare module 'reflux/src/index' {
  declare module.exports: any;
}

declare module 'reflux/src/joins' {
  declare module.exports: any;
}

declare module 'reflux/src/Keep' {
  declare module.exports: any;
}

declare module 'reflux/src/ListenerMethods' {
  declare module.exports: any;
}

declare module 'reflux/src/ListenerMixin' {
  declare module.exports: any;
}

declare module 'reflux/src/listenTo' {
  declare module.exports: any;
}

declare module 'reflux/src/listenToMany' {
  declare module.exports: any;
}

declare module 'reflux/src/PublisherMethods' {
  declare module.exports: any;
}

declare module 'reflux/src/utils' {
  declare module.exports: any;
}

declare module 'reflux/test/benchmarks/index' {
  declare module.exports: any;
}

declare module 'reflux/test/benchmarks/listeningToActions' {
  declare module.exports: any;
}

declare module 'reflux/test/benchmarks/listeningToJoins' {
  declare module.exports: any;
}

declare module 'reflux/test/benchmarks/listeningToStores' {
  declare module.exports: any;
}

declare module 'reflux/test/ceasingListens.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/changingEventStore.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/composedListenable.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/creatingActions.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/creatingAggregateStores.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/creatingStores.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/index' {
  declare module.exports: any;
}

declare module 'reflux/test/inspectWithKeep.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/listenTo.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/listenToMany.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/overridingEmitHooks.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/usingConnectMixin.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/usingJoins.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/usingListenerMethodsMixin.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/usingListenerMixin.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/usingPublisherMethodsMixin.spec' {
  declare module.exports: any;
}

declare module 'reflux/test/usingUtils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reflux/dist/reflux.js' {
  declare module.exports: $Exports<'reflux/dist/reflux'>;
}
declare module 'reflux/dist/reflux.min.js' {
  declare module.exports: $Exports<'reflux/dist/reflux.min'>;
}
declare module 'reflux/Gruntfile.js' {
  declare module.exports: $Exports<'reflux/Gruntfile'>;
}
declare module 'reflux/karma.conf.js' {
  declare module.exports: $Exports<'reflux/karma.conf'>;
}
declare module 'reflux/src/connect.js' {
  declare module.exports: $Exports<'reflux/src/connect'>;
}
declare module 'reflux/src/createAction.js' {
  declare module.exports: $Exports<'reflux/src/createAction'>;
}
declare module 'reflux/src/createStore.js' {
  declare module.exports: $Exports<'reflux/src/createStore'>;
}
declare module 'reflux/src/index.js' {
  declare module.exports: $Exports<'reflux/src/index'>;
}
declare module 'reflux/src/joins.js' {
  declare module.exports: $Exports<'reflux/src/joins'>;
}
declare module 'reflux/src/Keep.js' {
  declare module.exports: $Exports<'reflux/src/Keep'>;
}
declare module 'reflux/src/ListenerMethods.js' {
  declare module.exports: $Exports<'reflux/src/ListenerMethods'>;
}
declare module 'reflux/src/ListenerMixin.js' {
  declare module.exports: $Exports<'reflux/src/ListenerMixin'>;
}
declare module 'reflux/src/listenTo.js' {
  declare module.exports: $Exports<'reflux/src/listenTo'>;
}
declare module 'reflux/src/listenToMany.js' {
  declare module.exports: $Exports<'reflux/src/listenToMany'>;
}
declare module 'reflux/src/PublisherMethods.js' {
  declare module.exports: $Exports<'reflux/src/PublisherMethods'>;
}
declare module 'reflux/src/utils.js' {
  declare module.exports: $Exports<'reflux/src/utils'>;
}
declare module 'reflux/test/benchmarks/index.js' {
  declare module.exports: $Exports<'reflux/test/benchmarks/index'>;
}
declare module 'reflux/test/benchmarks/listeningToActions.js' {
  declare module.exports: $Exports<'reflux/test/benchmarks/listeningToActions'>;
}
declare module 'reflux/test/benchmarks/listeningToJoins.js' {
  declare module.exports: $Exports<'reflux/test/benchmarks/listeningToJoins'>;
}
declare module 'reflux/test/benchmarks/listeningToStores.js' {
  declare module.exports: $Exports<'reflux/test/benchmarks/listeningToStores'>;
}
declare module 'reflux/test/ceasingListens.spec.js' {
  declare module.exports: $Exports<'reflux/test/ceasingListens.spec'>;
}
declare module 'reflux/test/changingEventStore.spec.js' {
  declare module.exports: $Exports<'reflux/test/changingEventStore.spec'>;
}
declare module 'reflux/test/composedListenable.spec.js' {
  declare module.exports: $Exports<'reflux/test/composedListenable.spec'>;
}
declare module 'reflux/test/creatingActions.spec.js' {
  declare module.exports: $Exports<'reflux/test/creatingActions.spec'>;
}
declare module 'reflux/test/creatingAggregateStores.spec.js' {
  declare module.exports: $Exports<'reflux/test/creatingAggregateStores.spec'>;
}
declare module 'reflux/test/creatingStores.spec.js' {
  declare module.exports: $Exports<'reflux/test/creatingStores.spec'>;
}
declare module 'reflux/test/index.js' {
  declare module.exports: $Exports<'reflux/test/index'>;
}
declare module 'reflux/test/inspectWithKeep.spec.js' {
  declare module.exports: $Exports<'reflux/test/inspectWithKeep.spec'>;
}
declare module 'reflux/test/listenTo.spec.js' {
  declare module.exports: $Exports<'reflux/test/listenTo.spec'>;
}
declare module 'reflux/test/listenToMany.spec.js' {
  declare module.exports: $Exports<'reflux/test/listenToMany.spec'>;
}
declare module 'reflux/test/overridingEmitHooks.spec.js' {
  declare module.exports: $Exports<'reflux/test/overridingEmitHooks.spec'>;
}
declare module 'reflux/test/usingConnectMixin.spec.js' {
  declare module.exports: $Exports<'reflux/test/usingConnectMixin.spec'>;
}
declare module 'reflux/test/usingJoins.spec.js' {
  declare module.exports: $Exports<'reflux/test/usingJoins.spec'>;
}
declare module 'reflux/test/usingListenerMethodsMixin.spec.js' {
  declare module.exports: $Exports<'reflux/test/usingListenerMethodsMixin.spec'>;
}
declare module 'reflux/test/usingListenerMixin.spec.js' {
  declare module.exports: $Exports<'reflux/test/usingListenerMixin.spec'>;
}
declare module 'reflux/test/usingPublisherMethodsMixin.spec.js' {
  declare module.exports: $Exports<'reflux/test/usingPublisherMethodsMixin.spec'>;
}
declare module 'reflux/test/usingUtils.spec.js' {
  declare module.exports: $Exports<'reflux/test/usingUtils.spec'>;
}
