// flow-typed signature: fdaa8125cb8fa189b8f6e8ca291c876f
// flow-typed version: <<STUB>>/runas_v^3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'runas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'runas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'runas/lib/runas' {
  declare module.exports: any;
}

declare module 'runas/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'runas/lib/runas.js' {
  declare module.exports: $Exports<'runas/lib/runas'>;
}
declare module 'runas/test.js' {
  declare module.exports: $Exports<'runas/test'>;
}
