// flow-typed signature: b51d3c9f09957b927aa71908b1ac4897
// flow-typed version: <<STUB>>/rx-lite-testing_v^4.0.7/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx-lite-testing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx-lite-testing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rx-lite-testing/rx.lite.testing' {
  declare module.exports: any;
}

declare module 'rx-lite-testing/rx.lite.testing.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rx-lite-testing/rx.lite.testing.js' {
  declare module.exports: $Exports<'rx-lite-testing/rx.lite.testing'>;
}
declare module 'rx-lite-testing/rx.lite.testing.min.js' {
  declare module.exports: $Exports<'rx-lite-testing/rx.lite.testing.min'>;
}
