// flow-typed signature: 360015f90764b5acd83b671d489aa1c9
// flow-typed version: <<STUB>>/babel-preset-electron_v0.37.8/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-electron/index' {
  declare module.exports: $Exports<'babel-preset-electron'>;
}
declare module 'babel-preset-electron/index.js' {
  declare module.exports: $Exports<'babel-preset-electron'>;
}
