// flow-typed signature: 55fa7de11254e5ef031c90686fad2ea5
// flow-typed version: <<STUB>>/classnames_v1.2.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'classnames' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'classnames/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'classnames/index' {
  declare module.exports: $Exports<'classnames'>;
}
declare module 'classnames/index.js' {
  declare module.exports: $Exports<'classnames'>;
}
declare module 'classnames/tests.js' {
  declare module.exports: $Exports<'classnames/tests'>;
}
