// flow-typed signature: df4e79569df3ada1827daf3eb1b058cf
// flow-typed version: <<STUB>>/coffeestack_v^1.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffeestack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffeestack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'coffeestack/index' {
  declare module.exports: $Exports<'coffeestack'>;
}
declare module 'coffeestack/index.js' {
  declare module.exports: $Exports<'coffeestack'>;
}
