// flow-typed signature: dbc41794cadee594185d9e75f7b687b1
// flow-typed version: <<STUB>>/fs-plus_v^2.3.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-plus/lib/fs-plus' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-plus/lib/fs-plus.js' {
  declare module.exports: $Exports<'fs-plus/lib/fs-plus'>;
}
