// flow-typed signature: 596752c4ff197d9e9c571f8b7869fa77
// flow-typed version: <<STUB>>/jasmine-tagged_v^1.1.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-tagged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-tagged' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-tagged/lib/jasmine-tagged' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-tagged/lib/jasmine-tagged.js' {
  declare module.exports: $Exports<'jasmine-tagged/lib/jasmine-tagged'>;
}
