// flow-typed signature: 599f4da9ed3a5d47fdb6f06da200642c
// flow-typed version: <<STUB>>/jasmine-react-helpers_v^0.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-react-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-react-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-react-helpers/Gruntfile' {
  declare module.exports: any;
}

declare module 'jasmine-react-helpers/src/jasmine-react' {
  declare module.exports: any;
}

declare module 'jasmine-react-helpers/test/documentation-spec' {
  declare module.exports: any;
}

declare module 'jasmine-react-helpers/test/jasmine-react-spec' {
  declare module.exports: any;
}

declare module 'jasmine-react-helpers/test/support/jasmine-content' {
  declare module.exports: any;
}

declare module 'jasmine-react-helpers/test/support/phantomjs-shims' {
  declare module.exports: any;
}

declare module 'jasmine-react-helpers/test/support/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-react-helpers/Gruntfile.js' {
  declare module.exports: $Exports<'jasmine-react-helpers/Gruntfile'>;
}
declare module 'jasmine-react-helpers/src/jasmine-react.js' {
  declare module.exports: $Exports<'jasmine-react-helpers/src/jasmine-react'>;
}
declare module 'jasmine-react-helpers/test/documentation-spec.js' {
  declare module.exports: $Exports<'jasmine-react-helpers/test/documentation-spec'>;
}
declare module 'jasmine-react-helpers/test/jasmine-react-spec.js' {
  declare module.exports: $Exports<'jasmine-react-helpers/test/jasmine-react-spec'>;
}
declare module 'jasmine-react-helpers/test/support/jasmine-content.js' {
  declare module.exports: $Exports<'jasmine-react-helpers/test/support/jasmine-content'>;
}
declare module 'jasmine-react-helpers/test/support/phantomjs-shims.js' {
  declare module.exports: $Exports<'jasmine-react-helpers/test/support/phantomjs-shims'>;
}
declare module 'jasmine-react-helpers/test/support/react.js' {
  declare module.exports: $Exports<'jasmine-react-helpers/test/support/react'>;
}
