// flow-typed signature: 6ca8522dcb03314d4a75fd65aaba1cad
// flow-typed version: <<STUB>>/jasmine-json_v~0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-json/lib/matchers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-json/lib/matchers.js' {
  declare module.exports: $Exports<'jasmine-json/lib/matchers'>;
}
