// flow-typed signature: 15188e8a29f9a9553f8fa29a6c5bec3b
// flow-typed version: <<STUB>>/less-cache_v0.21/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-cache/lib/less-cache' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-cache/lib/less-cache.js' {
  declare module.exports: $Exports<'less-cache/lib/less-cache'>;
}
