// flow-typed signature: 777e090e8ab43287ade2fa7bae3f328c
// flow-typed version: <<STUB>>/optimist_v0.4.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optimist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'optimist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optimist/example/bool' {
  declare module.exports: any;
}

declare module 'optimist/example/boolean_double' {
  declare module.exports: any;
}

declare module 'optimist/example/boolean_single' {
  declare module.exports: any;
}

declare module 'optimist/example/default_hash' {
  declare module.exports: any;
}

declare module 'optimist/example/default_singles' {
  declare module.exports: any;
}

declare module 'optimist/example/divide' {
  declare module.exports: any;
}

declare module 'optimist/example/line_count_options' {
  declare module.exports: any;
}

declare module 'optimist/example/line_count_wrap' {
  declare module.exports: any;
}

declare module 'optimist/example/line_count' {
  declare module.exports: any;
}

declare module 'optimist/example/nonopt' {
  declare module.exports: any;
}

declare module 'optimist/example/reflect' {
  declare module.exports: any;
}

declare module 'optimist/example/short' {
  declare module.exports: any;
}

declare module 'optimist/example/string' {
  declare module.exports: any;
}

declare module 'optimist/example/usage-options' {
  declare module.exports: any;
}

declare module 'optimist/example/xup' {
  declare module.exports: any;
}

declare module 'optimist/test/_' {
  declare module.exports: any;
}

declare module 'optimist/test/_/argv' {
  declare module.exports: any;
}

declare module 'optimist/test/_/bin' {
  declare module.exports: any;
}

declare module 'optimist/test/parse' {
  declare module.exports: any;
}

declare module 'optimist/test/short' {
  declare module.exports: any;
}

declare module 'optimist/test/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optimist/example/bool.js' {
  declare module.exports: $Exports<'optimist/example/bool'>;
}
declare module 'optimist/example/boolean_double.js' {
  declare module.exports: $Exports<'optimist/example/boolean_double'>;
}
declare module 'optimist/example/boolean_single.js' {
  declare module.exports: $Exports<'optimist/example/boolean_single'>;
}
declare module 'optimist/example/default_hash.js' {
  declare module.exports: $Exports<'optimist/example/default_hash'>;
}
declare module 'optimist/example/default_singles.js' {
  declare module.exports: $Exports<'optimist/example/default_singles'>;
}
declare module 'optimist/example/divide.js' {
  declare module.exports: $Exports<'optimist/example/divide'>;
}
declare module 'optimist/example/line_count_options.js' {
  declare module.exports: $Exports<'optimist/example/line_count_options'>;
}
declare module 'optimist/example/line_count_wrap.js' {
  declare module.exports: $Exports<'optimist/example/line_count_wrap'>;
}
declare module 'optimist/example/line_count.js' {
  declare module.exports: $Exports<'optimist/example/line_count'>;
}
declare module 'optimist/example/nonopt.js' {
  declare module.exports: $Exports<'optimist/example/nonopt'>;
}
declare module 'optimist/example/reflect.js' {
  declare module.exports: $Exports<'optimist/example/reflect'>;
}
declare module 'optimist/example/short.js' {
  declare module.exports: $Exports<'optimist/example/short'>;
}
declare module 'optimist/example/string.js' {
  declare module.exports: $Exports<'optimist/example/string'>;
}
declare module 'optimist/example/usage-options.js' {
  declare module.exports: $Exports<'optimist/example/usage-options'>;
}
declare module 'optimist/example/xup.js' {
  declare module.exports: $Exports<'optimist/example/xup'>;
}
declare module 'optimist/index' {
  declare module.exports: $Exports<'optimist'>;
}
declare module 'optimist/index.js' {
  declare module.exports: $Exports<'optimist'>;
}
declare module 'optimist/test/_.js' {
  declare module.exports: $Exports<'optimist/test/_'>;
}
declare module 'optimist/test/_/argv.js' {
  declare module.exports: $Exports<'optimist/test/_/argv'>;
}
declare module 'optimist/test/_/bin.js' {
  declare module.exports: $Exports<'optimist/test/_/bin'>;
}
declare module 'optimist/test/parse.js' {
  declare module.exports: $Exports<'optimist/test/parse'>;
}
declare module 'optimist/test/short.js' {
  declare module.exports: $Exports<'optimist/test/short'>;
}
declare module 'optimist/test/usage.js' {
  declare module.exports: $Exports<'optimist/test/usage'>;
}
