// flow-typed signature: d42a8522f404e6a79d1925a75b846bdd
// flow-typed version: <<STUB>>/pathwatcher_v~6.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pathwatcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pathwatcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pathwatcher/lib/directory' {
  declare module.exports: any;
}

declare module 'pathwatcher/lib/file' {
  declare module.exports: any;
}

declare module 'pathwatcher/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pathwatcher/lib/directory.js' {
  declare module.exports: $Exports<'pathwatcher/lib/directory'>;
}
declare module 'pathwatcher/lib/file.js' {
  declare module.exports: $Exports<'pathwatcher/lib/file'>;
}
declare module 'pathwatcher/lib/main.js' {
  declare module.exports: $Exports<'pathwatcher/lib/main'>;
}
