// flow-typed signature: 1632f784535f7de406f52857457ab553
// flow-typed version: <<STUB>>/raven_v0.7.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raven'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'raven' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raven/example/app' {
  declare module.exports: any;
}

declare module 'raven/example/app2' {
  declare module.exports: any;
}

declare module 'raven/example/error' {
  declare module.exports: any;
}

declare module 'raven/example/views' {
  declare module.exports: any;
}

declare module 'raven/lib/client' {
  declare module.exports: any;
}

declare module 'raven/lib/middleware/connect' {
  declare module.exports: any;
}

declare module 'raven/lib/parsers' {
  declare module.exports: any;
}

declare module 'raven/lib/transports' {
  declare module.exports: any;
}

declare module 'raven/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raven/example/app.js' {
  declare module.exports: $Exports<'raven/example/app'>;
}
declare module 'raven/example/app2.js' {
  declare module.exports: $Exports<'raven/example/app2'>;
}
declare module 'raven/example/error.js' {
  declare module.exports: $Exports<'raven/example/error'>;
}
declare module 'raven/example/views.js' {
  declare module.exports: $Exports<'raven/example/views'>;
}
declare module 'raven/index' {
  declare module.exports: $Exports<'raven'>;
}
declare module 'raven/index.js' {
  declare module.exports: $Exports<'raven'>;
}
declare module 'raven/lib/client.js' {
  declare module.exports: $Exports<'raven/lib/client'>;
}
declare module 'raven/lib/middleware/connect.js' {
  declare module.exports: $Exports<'raven/lib/middleware/connect'>;
}
declare module 'raven/lib/parsers.js' {
  declare module.exports: $Exports<'raven/lib/parsers'>;
}
declare module 'raven/lib/transports.js' {
  declare module.exports: $Exports<'raven/lib/transports'>;
}
declare module 'raven/lib/utils.js' {
  declare module.exports: $Exports<'raven/lib/utils'>;
}
