// flow-typed signature: 44456e0d6bd980802ca901f6acc69ec1
// flow-typed version: <<STUB>>/source-map-support_v^0.3.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-support'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-support' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-map-support/amd-test/browser-source-map-support' {
  declare module.exports: any;
}

declare module 'source-map-support/amd-test/require' {
  declare module.exports: any;
}

declare module 'source-map-support/amd-test/script' {
  declare module.exports: any;
}

declare module 'source-map-support/browser-source-map-support' {
  declare module.exports: any;
}

declare module 'source-map-support/browser-test/script' {
  declare module.exports: any;
}

declare module 'source-map-support/build' {
  declare module.exports: any;
}

declare module 'source-map-support/header-test/script' {
  declare module.exports: any;
}

declare module 'source-map-support/header-test/server' {
  declare module.exports: any;
}

declare module 'source-map-support/register' {
  declare module.exports: any;
}

declare module 'source-map-support/source-map-support' {
  declare module.exports: any;
}

declare module 'source-map-support/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-map-support/amd-test/browser-source-map-support.js' {
  declare module.exports: $Exports<'source-map-support/amd-test/browser-source-map-support'>;
}
declare module 'source-map-support/amd-test/require.js' {
  declare module.exports: $Exports<'source-map-support/amd-test/require'>;
}
declare module 'source-map-support/amd-test/script.js' {
  declare module.exports: $Exports<'source-map-support/amd-test/script'>;
}
declare module 'source-map-support/browser-source-map-support.js' {
  declare module.exports: $Exports<'source-map-support/browser-source-map-support'>;
}
declare module 'source-map-support/browser-test/script.js' {
  declare module.exports: $Exports<'source-map-support/browser-test/script'>;
}
declare module 'source-map-support/build.js' {
  declare module.exports: $Exports<'source-map-support/build'>;
}
declare module 'source-map-support/header-test/script.js' {
  declare module.exports: $Exports<'source-map-support/header-test/script'>;
}
declare module 'source-map-support/header-test/server.js' {
  declare module.exports: $Exports<'source-map-support/header-test/server'>;
}
declare module 'source-map-support/register.js' {
  declare module.exports: $Exports<'source-map-support/register'>;
}
declare module 'source-map-support/source-map-support.js' {
  declare module.exports: $Exports<'source-map-support/source-map-support'>;
}
declare module 'source-map-support/test.js' {
  declare module.exports: $Exports<'source-map-support/test'>;
}
